apiVersion: v1
kind: Pod
metadata:
  name: node-api
spec:
  containers:
  - name: node-api-container
    image: node-api:latest
    ports:
    - containerPort: 3000
    securityContext:
      runAsUser: 0  # root, pour tester Conftest
