name: CI DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Lint YAML files
      uses: ibiqlik/action-yamllint@v3
      with:
        file_or_dir: './deployment.yaml'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t node-api .

    - name: Trivy FS (scan dépendances)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .

    - name: Trivy Image scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'node-api:latest'
        format: table
        ignore-unfixed: true
        vuln-type: os,library

    - name: Conftest (policy check)
      uses: instrumenta/conftest-action@master
      with:
        files: deployment.yaml
        policy-path: ./policy
